server:
  port: 9002

spring:
  application:
    name: nacos-provider-v2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  basePackage: com.example.nacos.controller
  title: NACOS
  description: NACOS-TEST
  version: 1.0
  author: cxh
  url: http://www.bbdtek.com
  email: 1078488837@qq.com
