server:
  port: 9101

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server-url:
  nacos-user-service: http://nacos-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  basePackage: com.example.nacos.controller
  title: NACOS
  description: NACOS-TEST
  version: 1.0
  author: cxh
  url: http://www.bbdtek.com
  email: 1078488837@qq.com
